// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestingSystem.Data.Sqlite;

#nullable disable

namespace TestingSystem.Data.Sqlite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250704141143_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("ImageQuestion", b =>
                {
                    b.Property<Guid>("ImagesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.HasKey("ImagesId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("ImageQuestion");
                });

            modelBuilder.Entity("TestingSystem.Core.Models.AnswerOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswersOptions");
                });

            modelBuilder.Entity("TestingSystem.Core.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("TestingSystem.Core.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("TestingSystem.Core.Models.Score", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AnswerOptionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnswerOptionId")
                        .IsUnique();

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("TestingSystem.Core.Models.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("TestingSystem.Core.Models.TestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ScoreId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TestId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScoreId")
                        .IsUnique();

                    b.HasIndex("TestId");

                    b.HasIndex("UserId");

                    b.ToTable("TestsResults");
                });

            modelBuilder.Entity("TestingSystem.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TestingSystem.Core.Models.UserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnswerOptionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TestResultId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TestResultId1")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnswerOptionId");

                    b.HasIndex("TestResultId");

                    b.HasIndex("TestResultId1");

                    b.ToTable("UsersAnswers");
                });

            modelBuilder.Entity("TestingSystem.Core.Models.Vector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vectors");
                });

            modelBuilder.Entity("TestingSystem.Core.Models.VectorScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScoreId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.Property<Guid>("VectorId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScoreId");

                    b.HasIndex("VectorId");

                    b.ToTable("VectorsScores");
                });

            modelBuilder.Entity("ImageQuestion", b =>
                {
                    b.HasOne("TestingSystem.Core.Models.Image", null)
                        .WithMany()
                        .HasForeignKey("ImagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestingSystem.Core.Models.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestingSystem.Core.Models.AnswerOption", b =>
                {
                    b.HasOne("TestingSystem.Core.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TestingSystem.Core.Models.Question", "Question")
                        .WithMany("AnswersOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("TestingSystem.Core.Models.Question", b =>
                {
                    b.HasOne("TestingSystem.Core.Models.Test", "Test")
                        .WithMany("Questions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("TestingSystem.Core.Models.Score", b =>
                {
                    b.HasOne("TestingSystem.Core.Models.AnswerOption", "AnswerOption")
                        .WithOne("Score")
                        .HasForeignKey("TestingSystem.Core.Models.Score", "AnswerOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AnswerOption");
                });

            modelBuilder.Entity("TestingSystem.Core.Models.Test", b =>
                {
                    b.HasOne("TestingSystem.Core.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Image");
                });

            modelBuilder.Entity("TestingSystem.Core.Models.TestResult", b =>
                {
                    b.HasOne("TestingSystem.Core.Models.Score", "Score")
                        .WithOne("TestResult")
                        .HasForeignKey("TestingSystem.Core.Models.TestResult", "ScoreId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TestingSystem.Core.Models.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TestingSystem.Core.Models.User", "User")
                        .WithMany("TestsResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Score");

                    b.Navigation("Test");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TestingSystem.Core.Models.User", b =>
                {
                    b.HasOne("TestingSystem.Core.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Image");
                });

            modelBuilder.Entity("TestingSystem.Core.Models.UserAnswer", b =>
                {
                    b.HasOne("TestingSystem.Core.Models.AnswerOption", "AnswerOption")
                        .WithMany()
                        .HasForeignKey("AnswerOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TestingSystem.Core.Models.TestResult", "TestResult")
                        .WithMany()
                        .HasForeignKey("TestResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestingSystem.Core.Models.TestResult", null)
                        .WithMany("UserAnswers")
                        .HasForeignKey("TestResultId1");

                    b.Navigation("AnswerOption");

                    b.Navigation("TestResult");
                });

            modelBuilder.Entity("TestingSystem.Core.Models.VectorScore", b =>
                {
                    b.HasOne("TestingSystem.Core.Models.Score", "Score")
                        .WithMany("VectorsScores")
                        .HasForeignKey("ScoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TestingSystem.Core.Models.Vector", "Vector")
                        .WithMany()
                        .HasForeignKey("VectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Score");

                    b.Navigation("Vector");
                });

            modelBuilder.Entity("TestingSystem.Core.Models.AnswerOption", b =>
                {
                    b.Navigation("Score")
                        .IsRequired();
                });

            modelBuilder.Entity("TestingSystem.Core.Models.Question", b =>
                {
                    b.Navigation("AnswersOptions");
                });

            modelBuilder.Entity("TestingSystem.Core.Models.Score", b =>
                {
                    b.Navigation("TestResult");

                    b.Navigation("VectorsScores");
                });

            modelBuilder.Entity("TestingSystem.Core.Models.Test", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("TestingSystem.Core.Models.TestResult", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("TestingSystem.Core.Models.User", b =>
                {
                    b.Navigation("TestsResults");
                });
#pragma warning restore 612, 618
        }
    }
}
