// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestingSystem.Data.Sqlite;

#nullable disable

namespace TestingSystem.Data.Sqlite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("ImageEntityQuestionEntity", b =>
                {
                    b.Property<int>("ImagesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionEntityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ImagesId", "QuestionEntityId");

                    b.HasIndex("QuestionEntityId");

                    b.ToTable("ImageEntityQuestionEntity");
                });

            modelBuilder.Entity("TestingSystem.Data.Sqlite.Entities.AnswerOptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ScoreId");

                    b.ToTable("AnswersOptions");
                });

            modelBuilder.Entity("TestingSystem.Data.Sqlite.Entities.ImageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("TestingSystem.Data.Sqlite.Entities.QuestionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("TestingSystem.Data.Sqlite.Entities.ScoreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("TestingSystem.Data.Sqlite.Entities.TestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ImageId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("TestingSystem.Data.Sqlite.Entities.TestResultEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScoreId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.HasIndex("UserId");

                    b.ToTable("TestsResults");
                });

            modelBuilder.Entity("TestingSystem.Data.Sqlite.Entities.UserAnswerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnswerOptionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TestResultEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestResultId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnswerOptionId");

                    b.HasIndex("TestResultEntityId");

                    b.HasIndex("TestResultId");

                    b.ToTable("UsersAnswers");
                });

            modelBuilder.Entity("TestingSystem.Data.Sqlite.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TestingSystem.Data.Sqlite.Entities.VectorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Vectors");
                });

            modelBuilder.Entity("TestingSystem.Data.Sqlite.Entities.VectorScoreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.Property<int>("VectorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScoreId");

                    b.HasIndex("VectorId");

                    b.ToTable("VectorsScores");
                });

            modelBuilder.Entity("ImageEntityQuestionEntity", b =>
                {
                    b.HasOne("TestingSystem.Data.Sqlite.Entities.ImageEntity", null)
                        .WithMany()
                        .HasForeignKey("ImagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestingSystem.Data.Sqlite.Entities.QuestionEntity", null)
                        .WithMany()
                        .HasForeignKey("QuestionEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestingSystem.Data.Sqlite.Entities.AnswerOptionEntity", b =>
                {
                    b.HasOne("TestingSystem.Data.Sqlite.Entities.ImageEntity", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TestingSystem.Data.Sqlite.Entities.QuestionEntity", "Question")
                        .WithMany("AnswersOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestingSystem.Data.Sqlite.Entities.ScoreEntity", "Score")
                        .WithMany()
                        .HasForeignKey("ScoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Question");

                    b.Navigation("Score");
                });

            modelBuilder.Entity("TestingSystem.Data.Sqlite.Entities.QuestionEntity", b =>
                {
                    b.HasOne("TestingSystem.Data.Sqlite.Entities.TestEntity", "Test")
                        .WithMany("Questions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("TestingSystem.Data.Sqlite.Entities.TestEntity", b =>
                {
                    b.HasOne("TestingSystem.Data.Sqlite.Entities.UserEntity", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestingSystem.Data.Sqlite.Entities.ImageEntity", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("TestingSystem.Data.Sqlite.Entities.TestResultEntity", b =>
                {
                    b.HasOne("TestingSystem.Data.Sqlite.Entities.TestEntity", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TestingSystem.Data.Sqlite.Entities.UserEntity", "User")
                        .WithMany("TestsResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TestingSystem.Data.Sqlite.Entities.UserAnswerEntity", b =>
                {
                    b.HasOne("TestingSystem.Data.Sqlite.Entities.AnswerOptionEntity", "AnswerOption")
                        .WithMany()
                        .HasForeignKey("AnswerOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TestingSystem.Data.Sqlite.Entities.TestResultEntity", null)
                        .WithMany("UserAnswers")
                        .HasForeignKey("TestResultEntityId");

                    b.HasOne("TestingSystem.Data.Sqlite.Entities.TestResultEntity", "TestResult")
                        .WithMany()
                        .HasForeignKey("TestResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnswerOption");

                    b.Navigation("TestResult");
                });

            modelBuilder.Entity("TestingSystem.Data.Sqlite.Entities.UserEntity", b =>
                {
                    b.HasOne("TestingSystem.Data.Sqlite.Entities.ImageEntity", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Image");
                });

            modelBuilder.Entity("TestingSystem.Data.Sqlite.Entities.VectorScoreEntity", b =>
                {
                    b.HasOne("TestingSystem.Data.Sqlite.Entities.ScoreEntity", "Score")
                        .WithMany("VectorsScores")
                        .HasForeignKey("ScoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TestingSystem.Data.Sqlite.Entities.VectorEntity", "Vector")
                        .WithMany()
                        .HasForeignKey("VectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Score");

                    b.Navigation("Vector");
                });

            modelBuilder.Entity("TestingSystem.Data.Sqlite.Entities.QuestionEntity", b =>
                {
                    b.Navigation("AnswersOptions");
                });

            modelBuilder.Entity("TestingSystem.Data.Sqlite.Entities.ScoreEntity", b =>
                {
                    b.Navigation("VectorsScores");
                });

            modelBuilder.Entity("TestingSystem.Data.Sqlite.Entities.TestEntity", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("TestingSystem.Data.Sqlite.Entities.TestResultEntity", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("TestingSystem.Data.Sqlite.Entities.UserEntity", b =>
                {
                    b.Navigation("TestsResults");
                });
#pragma warning restore 612, 618
        }
    }
}
